### ISSUE TITLE
Remove use of "MOTODEV Studio"

### ISSUE THREAD

**Issue by ehcloninger** [kingargyle/andmore#20]
The term MOTODEV Studio should be deprecated and renamed before we publish.

I'd prefer to not use the word "Studio" as it's too widely used for a variety of purposes.

Ideas?

Andmore Tools for X
Supplemental Tools
...

**Comment by kingargyle** [comment]
We'll be transferring owner ship to eclipse starting today.  Eventually this issue tracker will be closed.  Please open bugs at  https://bugs.eclipse.org/bugs/enter_bug.cgi?product=andmore.
