### ISSUE TITLE
Need license terms for former MOTODEV plugins

### ISSUE THREAD

**Issue by ehcloninger** [kingargyle/andmore#21]
The MOTODEV group of plugins has a placeholder for license terms. Text says "place your license text here".

![license](https://cloud.githubusercontent.com/assets/398033/5495421/2b4af014-86c3-11e4-9b25-09f4e1c8bc83.png)

**Comment by kingargyle** [comment]
We'll be transferring owner ship to eclipse starting today.  Eventually this issue tracker will be closed.  Please open bugs at  https://bugs.eclipse.org/bugs/enter_bug.cgi?product=andmore.
