### ISSUE TITLE
Clean up feature names and remove redundancies

### ISSUE THREAD

**Issue by ehcloninger** [kingargyle/andmore#23]
I see a lot of nested features and what appear to be name conflicts. Can this list be tightened up? It seems like a lot of things to install/uninstall.

![feature_names](https://cloud.githubusercontent.com/assets/398033/5495226/6b8a0856-86c1-11e4-8395-375a546f3a3f.png)

**Comment by kingargyle** [comment]
We'll be transferring owner ship to eclipse starting today.  Eventually this issue tracker will be closed.  Please open bugs at  https://bugs.eclipse.org/bugs/enter_bug.cgi?product=andmore.
