### ISSUE TITLE
[Discuss] Remove emulator view from Andmore (nee proteus) perspective

### ISSUE THREAD

**Issue by ehcloninger** [kingargyle/andmore#26]
Should we remove the emulator view from the Andmore perspective and possibly from the project entirely? 

This was a cool feature in MOTODEV Studio 5 years ago, but it's a bit of a relic now. It was always difficult to keep this code up-to-date because of the complexity of the drawing calls. All supported platforms had to be implemented in different manners.

New emulator technologies, such as AndroidX86 and Genymotion aren't supported.

xxhdpi displays end up scaled inside the window. This could be seen as an advantage as well.

Removing it will reduce the dependency on the older parts of org.eclipse.sequoyah that were inherited from org.eclipse.dsdp.tml, circa 2008.

**Comment by kingargyle** [comment]
We'll be transferring owner ship to eclipse starting today.  Eventually this issue tracker will be closed.  Please open bugs at  https://bugs.eclipse.org/bugs/enter_bug.cgi?product=andmore.

Should continue disucssion at eclipse bug tracker or on the Andmore Dev mailing list.
