### ISSUE TITLE
link to clahub still references kingargyle/proteus

### ISSUE THREAD

**Issue by rtack** [kingargyle/andmore#35]
https://www.clahub.com/agreements/kingargyle/proteus
"Agreement for kingargyle/proteus"

change to andmore

**Comment by kingargyle** [comment]
I'll keep this open for right now.  Once we finish renaming, we'll be turning the repositiory over to the eclipse foundation, and all of these links will go away as well as the CLA service.  Bugzilla will be the place soon where all issues will be taking place.

**Comment by kingargyle** [comment]
We'll be transfering owner ship to eclipse starting today.  Eventually this issue tracker will be closed.  Please open bugs at  https://bugs.eclipse.org/bugs/enter_bug.cgi?product=andmore.
